### ISSUE TITLE
de.NBI Cloud Sites

### ISSUE THREAD

**Issue by pbelmann** [deNBI/cloud-user-docs#18]
All de.NBI Cloud sites should provide  URL and Support Email in the Cloud Center specific section.

- [x] Freiburg
- [x] Tübingen
- [x] Heidelberg
- [x] Bielefeld
- [x] Giessen

**Comment by erasche** [comment]
Just checked, looks like everyone added both URL + an email address.

**Comment by pbelmann** [comment]
Thanks @erasche .
