### ISSUE TITLE
non working links

### ISSUE THREAD

**Issue by eKatchko** [deNBI/cloud-user-docs#321]
- /html/Compute_Center/Bielefeld/index.html
  *  External link http://apt-cache.bi.denbi.de:9999 failed: got a time out (response code 0)

- /html/cloud_admin/juju_jenkins/index.html
  *  External link https://jaas.ai/u/lazypower/docker/23 failed: 404 No error

**Comment by NaincyKumariKnoldus** [comment]
Hey @eKatchko Can I fix this? can you provide me the correct links.

**Comment by eKatchko** [comment]
Hey @NaincyKumariKnoldus thank you for the offer.
If you want to, you can try to fix this.
The first link (http://apt-cache.bi.denbi.de:9999/) needs to be added to the whitelist.txt and the second link will be removed by us as we probably are going to remove the whole juju_jenkins.md.
